apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: device-registry
  labels:
    app: device-registry
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: device-registry
  labels:
    app: device-registry
spec:
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 1
  output:
    to:
      kind: ImageStreamTag
      name: device-registry:latest
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy: 
      dockerfilePath: device-registry/Dockerfile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-registry
  labels:
    app: device-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-registry
  template:
    metadata:
      labels:
        app: device-registry
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: device-registry
        image: image-registry.openshift-image-registry.svc:5000/atakangul-dev/device-registry:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: devices
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
              optional: true
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
              optional: true
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: device-registry
  labels:
    app: device-registry
spec:
  selector:
    app: device-registry
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  username: iot
  password: iot123
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: device-registry
  labels:
    app: device-registry
spec:
  to:
    kind: Service
    name: device-registry
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
