apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-config
data:
  GIT_REPO: "https://github.com/atakang7/iot-analytics.git"
  GIT_BRANCH: "main"
  POLL_INTERVAL: "60"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-script
data:
  controller.sh: |
    #!/bin/bash
    set -o pipefail
    
    WORKDIR="/tmp/repo"
    STATE="/tmp/last_commit"
    OC="/tmp/oc"
    
    JAVA_SERVICES="ingestion device-registry"
    PYTHON_WORKERS="telemetry-worker stream-worker alert-worker"
    
    log() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] [$1] $2"; }
    
    notify() {
      local ok=$1 msg=$2
      [[ "$ok" == "true" ]] && icon="✅" || icon="❌"
      log "INFO" "$icon $msg"
      [[ -n "$SLACK_WEBHOOK" ]] && curl -s -X POST "$SLACK_WEBHOOK" \
        -H "Content-Type: application/json" -d "{\"text\":\"$icon $msg\"}" >/dev/null 2>&1
    }
    
    setup_oc() {
      [[ -f "$OC" ]] && return 0
      log "INFO" "Downloading oc CLI..."
      curl -sL https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz | tar -xz -C /tmp oc
      chmod +x "$OC"
      log "INFO" "oc CLI ready"
    }
    
    get_remote_commit() {
      local url="$GIT_REPO"
      [[ -n "$GIT_TOKEN" ]] && url="${url/https:\/\//https://${GIT_TOKEN}@}"
      git ls-remote "$url" "refs/heads/$GIT_BRANCH" 2>/dev/null | cut -c1-12
    }
    
    clone_or_pull() {
      local url="$GIT_REPO"
      [[ -n "$GIT_TOKEN" ]] && url="${url/https:\/\//https://${GIT_TOKEN}@}"
      if [[ -d "$WORKDIR" ]]; then
        cd "$WORKDIR" && git fetch origin && git reset --hard "origin/$GIT_BRANCH"
      else
        git clone --branch "$GIT_BRANCH" --depth 50 "$url" "$WORKDIR"
      fi
    }
    
    build_deploy() {
      local component=$1 path=$2
      log "INFO" "Building $component..."
      cd "$WORKDIR"
      if $OC start-build "$component" --from-dir="$path" --follow --wait; then
        $OC rollout restart "deployment/$component"
        return 0
      fi
      return 1
    }
    
    process_changes() {
      local old=$1 new=$2
      [[ -z "$old" ]] && return
      
      cd "$WORKDIR"
      local files=$(git diff --name-only "$old" "$new" 2>/dev/null)
      [[ -z "$files" ]] && return
      
      local success="" failed=""
      
      for svc in $JAVA_SERVICES; do
        if echo "$files" | grep -q "^services/$svc/"; then
          build_deploy "$svc" "services/$svc" && success="$success $svc" || failed="$failed $svc"
        fi
      done
      
      for wrk in $PYTHON_WORKERS; do
        if echo "$files" | grep -q "^workers/$wrk/"; then
          build_deploy "$wrk" "workers/$wrk" && success="$success $wrk" || failed="$failed $wrk"
        fi
      done
      
      [[ -n "$success" ]] && notify "true" "Deployed:$success"
      [[ -n "$failed" ]] && notify "false" "Failed:$failed"
    }
    
    log "INFO" "GitOps Controller | Repo: $GIT_REPO | Branch: $GIT_BRANCH | Poll: ${POLL_INTERVAL}s"
    setup_oc || exit 1
    
    last=""
    [[ -f "$STATE" ]] && last=$(cat "$STATE")
    
    while true; do
      commit=$(get_remote_commit)
      [[ -z "$commit" || "$commit" == "$last" ]] && { sleep "$POLL_INTERVAL"; continue; }
      
      log "INFO" "New commit: $commit"
      clone_or_pull || { sleep "$POLL_INTERVAL"; continue; }
      
      process_changes "$last" "$commit"
      
      last="$commit"
      echo "$last" > "$STATE"
      sleep "$POLL_INTERVAL"
    done
---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-secret
stringData:
  GIT_TOKEN: ""
  SLACK_WEBHOOK: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-controller-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: gitops-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-controller
  labels:
    app: gitops-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-controller
  template:
    metadata:
      labels:
        app: gitops-controller
    spec:
      serviceAccountName: gitops-controller
      containers:
        - name: controller
          image: bitnami/git:latest
          command: ["bash", "/scripts/controller.sh"]
          env:
            - name: HOME
              value: /tmp
          envFrom:
            - configMapRef:
                name: gitops-config
            - secretRef:
                name: gitops-secret
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: scripts
          configMap:
            name: gitops-script
            defaultMode: 0755