---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kpi-job
  labels:
    app: kpi-job
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: kpi-job
        spec:
          restartPolicy: OnFailure
          initContainers:
            - name: wait-for-db
              image: busybox:1.36
              command: ['sh', '-c', 'until nc -z timescaledb 5432; do echo waiting for db; sleep 2; done']
          containers:
            - name: kpi-job
              image: image-registry.openshift-image-registry.svc:5000/atakangul-dev/kpi-job:latest
              env:
                - name: SERVICE_NAME
                  value: kpi-job
                - name: DB_HOST
                  value: timescaledb
                - name: DB_PORT
                  value: "5432"
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: iot-central-secret
                      key: timescaledb_db
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: iot-central-secret
                      key: timescaledb_user
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: iot-central-secret
                      key: timescaledb_password
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 300m
                  memory: 256Mi
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: kpi-worker
  labels:
    app: kpi-worker
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: kpi-worker
  labels:
    app: kpi-worker
spec:
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 1
  output:
    to:
      kind: ImageStreamTag
      name: kpi-worker:latest
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile