apiVersion: v1
kind: ConfigMap
metadata:
  name: timescaledb-init
data:
  schema.sql: |
{{ .Files.Get "configs/schema.sql" | indent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  labels:
    app: timescaledb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: timescale/timescaledb:latest-pg15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: iot-central-secret
                  key: timescaledb_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: iot-central-secret
                  key: timescaledb_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: iot-central-secret
                  key: timescaledb_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2"
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "iot", "-d", "iot"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "iot", "-d", "iot"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: timescaledb-pvc
        - name: init-scripts
          configMap:
            name: timescaledb-init
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: timescaledb