apiVersion: v1
kind: ConfigMap
metadata:
  name: timescaledb-config
  labels:
    app: timescaledb
data:
  POSTGRES_DB: "iot_timeseries"
  POSTGRES_USER: "iot"
  TIMESCALEDB_TELEMETRY: "off"
  TS_TUNE_MEMORY: "2GB"
  TS_TUNE_NUM_CPUS: "2"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: timescaledb-init
  labels:
    app: timescaledb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-pvc
  labels:
    app: timescaledb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.timescaledb.storage | default "20Gi" }}
  storageClassName: {{ .Values.timescaledb.storageClass | default "standard" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  labels:
    app: timescaledb
spec:
  replicas: 1
  strategy:
    type: Recreate  # Required for RWO PVC
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: timescale/timescaledb:latest-pg15
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - configMapRef:
                name: timescaledb-config
            - secretRef:
              name: iot-central-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2"
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "iot", "-d", "iot_timeseries"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "iot", "-d", "iot_timeseries"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: timescaledb-pvc
        - name: init-scripts
          configMap:
            name: timescaledb-init
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  labels:
    app: timescaledb
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: timescaledb