apiVersion: v1
kind: ConfigMap
metadata:
  name: timescaledb-config
  labels:
    app: timescaledb
data:
  POSTGRES_DB: "iot_timeseries"
  POSTGRES_USER: "iot"
  # Tune for time-series workload
  TIMESCALEDB_TELEMETRY: "off"
  TS_TUNE_MEMORY: "2GB"
  TS_TUNE_NUM_CPUS: "2"
---
apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-secret
  labels:
    app: timescaledb
type: Opaque
stringData:
  POSTGRES_PASSWORD: "changeme"  # Override in values.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: timescaledb-init
  labels:
    app: timescaledb
data:
  init.sql: |
    -- Enable TimescaleDB extension
    CREATE EXTENSION IF NOT EXISTS timescaledb;

    -- Raw telemetry hypertable
    CREATE TABLE IF NOT EXISTS telemetry (
        time        TIMESTAMPTZ NOT NULL,
        device_id   TEXT NOT NULL,
        sensor_type TEXT NOT NULL,
        value       DOUBLE PRECISION,
        metadata    JSONB
    );
    SELECT create_hypertable('telemetry', 'time', if_not_exists => TRUE);

    -- Compression policy (compress chunks older than 7 days)
    ALTER TABLE telemetry SET (
        timescaledb.compress,
        timescaledb.compress_segmentby = 'device_id,sensor_type'
    );
    SELECT add_compression_policy('telemetry', INTERVAL '7 days', if_not_exists => TRUE);

    -- Retention policy (drop data older than 90 days)
    SELECT add_retention_policy('telemetry', INTERVAL '90 days', if_not_exists => TRUE);

    -- Continuous aggregate for hourly rollups
    CREATE MATERIALIZED VIEW IF NOT EXISTS telemetry_hourly
    WITH (timescaledb.continuous) AS
    SELECT
        time_bucket('1 hour', time) AS bucket,
        device_id,
        sensor_type,
        avg(value) AS avg_value,
        min(value) AS min_value,
        max(value) AS max_value,
        count(*) AS sample_count
    FROM telemetry
    GROUP BY bucket, device_id, sensor_type
    WITH NO DATA;

    SELECT add_continuous_aggregate_policy('telemetry_hourly',
        start_offset => INTERVAL '3 hours',
        end_offset => INTERVAL '1 hour',
        schedule_interval => INTERVAL '1 hour',
        if_not_exists => TRUE
    );

    -- Alerts table
    CREATE TABLE IF NOT EXISTS alerts (
        time        TIMESTAMPTZ NOT NULL,
        device_id   TEXT NOT NULL,
        alert_type  TEXT NOT NULL,
        severity    TEXT NOT NULL,
        message     TEXT,
        acknowledged BOOLEAN DEFAULT FALSE
    );
    SELECT create_hypertable('alerts', 'time', if_not_exists => TRUE);

    -- Indexes
    CREATE INDEX IF NOT EXISTS idx_telemetry_device ON telemetry (device_id, time DESC);
    CREATE INDEX IF NOT EXISTS idx_alerts_device ON alerts (device_id, time DESC);
    CREATE INDEX IF NOT EXISTS idx_alerts_unack ON alerts (acknowledged, time DESC) WHERE NOT acknowledged;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-pvc
  labels:
    app: timescaledb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.timescaledb.storage | default "20Gi" }}
  storageClassName: {{ .Values.timescaledb.storageClass | default "standard" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  labels:
    app: timescaledb
spec:
  replicas: 1
  strategy:
    type: Recreate  # Required for RWO PVC
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: timescale/timescaledb:latest-pg15
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - configMapRef:
                name: timescaledb-config
            - secretRef:
                name: timescaledb-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2"
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "iot", "-d", "iot_timeseries"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "iot", "-d", "iot_timeseries"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: timescaledb-pvc
        - name: init-scripts
          configMap:
            name: timescaledb-init
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  labels:
    app: timescaledb
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: timescaledb