{{- if .Values.gitops.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-config
data:
  GIT_REPO: {{ .Values.gitops.repo | quote }}
  GIT_BRANCH: {{ .Values.gitops.branch | quote }}
  POLL_INTERVAL: {{ .Values.gitops.pollInterval | quote }}
  JAVA_SERVICES: {{ .Values.gitops.java.services | join " " | quote }}
  PYTHON_WORKERS: {{ .Values.gitops.python.workers | join " " | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-script
data:
  controller.sh: |
{{ .Files.Get "scripts/controller.sh" | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-secret
type: Opaque
stringData:
  GIT_TOKEN: {{ .Values.gitops.token | default "" | quote }}
  SLACK_WEBHOOK: {{ .Values.gitops.slack | default "" | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-controller-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: gitops-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-controller
  labels:
    app: gitops-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-controller
  template:
    metadata:
      labels:
        app: gitops-controller
      annotations:
        checksum/script: {{ .Files.Get "scripts/controller.sh" | sha256sum }}
        checksum/config: {{ toJson .Values.gitops | sha256sum }}
    spec:
      serviceAccountName: gitops-controller
      containers:
        - name: controller
          image: {{ .Values.gitops.image | default "bitnami/git:latest" }}
          command: ["bash", "/scripts/controller.sh"]
          env:
            - name: HOME
              value: /tmp
          envFrom:
            - configMapRef:
                name: gitops-config
            - secretRef:
                name: gitops-secret
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 2Gi
      volumes:
        - name: scripts
          configMap:
            name: gitops-script
            defaultMode: 0755
{{- end }}