package com.iot.common.dto.alert;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.iot.common.model.DeviceType;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.time.Instant;

/**
 * Alert message generated by Flink when anomalies are detected.
 * Sent to Kafka alerts topic, then routed to Alertmanager and stored in Postgres.
 *
 * Example JSON:
 * {
 *   "alertId": "alert-123",
 *   "deviceId": "cnc-001",
 *   "deviceType": "cnc_machine",
 *   "alertType": "high_vibration",
 *   "severity": "critical",
 *   "message": "Vibration RMS 3.5g exceeds threshold 2.0g",
 *   "kpiName": "vibration_rms",
 *   "kpiValue": 3.5,
 *   "threshold": 2.0,
 *   "windowStart": "2024-01-15T10:30:00Z",
 *   "windowEnd": "2024-01-15T10:31:00Z",
 *   "createdAt": "2024-01-15T10:31:05Z"
 * }
 */
public record AlertMessage(
    @NotBlank
    @JsonProperty("alertId")
    String alertId,

    @NotBlank
    @JsonProperty("deviceId")
    String deviceId,

    @NotNull
    @JsonProperty("deviceType")
    DeviceType deviceType,

    @NotNull
    @JsonProperty("alertType")
    AlertType alertType,

    @NotNull
    @JsonProperty("severity")
    AlertSeverity severity,

    @NotBlank
    @JsonProperty("message")
    String message,

    @JsonProperty("kpiName")
    String kpiName,

    @JsonProperty("kpiValue")
    Double kpiValue,

    @JsonProperty("threshold")
    Double threshold,

    @JsonProperty("windowStart")
    Instant windowStart,

    @JsonProperty("windowEnd")
    Instant windowEnd,

    @NotNull
    @JsonProperty("createdAt")
    Instant createdAt
) {
    @JsonCreator
    public AlertMessage(
        @JsonProperty("alertId") String alertId,
        @JsonProperty("deviceId") String deviceId,
        @JsonProperty("deviceType") DeviceType deviceType,
        @JsonProperty("alertType") AlertType alertType,
        @JsonProperty("severity") AlertSeverity severity,
        @JsonProperty("message") String message,
        @JsonProperty("kpiName") String kpiName,
        @JsonProperty("kpiValue") Double kpiValue,
        @JsonProperty("threshold") Double threshold,
        @JsonProperty("windowStart") Instant windowStart,
        @JsonProperty("windowEnd") Instant windowEnd,
        @JsonProperty("createdAt") Instant createdAt
    ) {
        this.alertId = alertId;
        this.deviceId = deviceId;
        this.deviceType = deviceType;
        this.alertType = alertType;
        this.severity = severity;
        this.message = message;
        this.kpiName = kpiName;
        this.kpiValue = kpiValue;
        this.threshold = threshold;
        this.windowStart = windowStart;
        this.windowEnd = windowEnd;
        this.createdAt = createdAt;
    }

    /**
     * Builder for creating AlertMessage instances.
     */
    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {
        private String alertId;
        private String deviceId;
        private DeviceType deviceType;
        private AlertType alertType;
        private AlertSeverity severity;
        private String message;
        private String kpiName;
        private Double kpiValue;
        private Double threshold;
        private Instant windowStart;
        private Instant windowEnd;
        private Instant createdAt;

        public Builder alertId(String alertId) { this.alertId = alertId; return this; }
        public Builder deviceId(String deviceId) { this.deviceId = deviceId; return this; }
        public Builder deviceType(DeviceType deviceType) { this.deviceType = deviceType; return this; }
        public Builder alertType(AlertType alertType) { this.alertType = alertType; return this; }
        public Builder severity(AlertSeverity severity) { this.severity = severity; return this; }
        public Builder message(String message) { this.message = message; return this; }
        public Builder kpiName(String kpiName) { this.kpiName = kpiName; return this; }
        public Builder kpiValue(Double kpiValue) { this.kpiValue = kpiValue; return this; }
        public Builder threshold(Double threshold) { this.threshold = threshold; return this; }
        public Builder windowStart(Instant windowStart) { this.windowStart = windowStart; return this; }
        public Builder windowEnd(Instant windowEnd) { this.windowEnd = windowEnd; return this; }
        public Builder createdAt(Instant createdAt) { this.createdAt = createdAt; return this; }

        public AlertMessage build() {
            return new AlertMessage(
                alertId, deviceId, deviceType, alertType, severity, message,
                kpiName, kpiValue, threshold, windowStart, windowEnd,
                createdAt != null ? createdAt : Instant.now()
            );
        }
    }
}
