# .github/actions/setup-oc/action.yaml
name: 'Setup OpenShift CLI'
description: 'Install oc CLI and login to cluster'

inputs:
  server:
    description: 'OpenShift API server URL'
    required: true
  token:
    description: 'OpenShift service account token'
    required: true
  namespace:
    description: 'Target namespace'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install oc CLI
      shell: bash
      run: |
        curl -sL https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz | tar -xz
        sudo mv oc /usr/local/bin/
        oc version --client

    - name: Login to OpenShift
      shell: bash
      run: |
        oc login --token=${{ inputs.token }} --server=${{ inputs.server }} --insecure-skip-tls-verify=true
        oc project ${{ inputs.namespace }}
